### ISSUE TITLE
DataLifecycle: CreateBucket Lifecycle always keeping the latest and removing other rules

### ISSUE THREAD

**Issue by satya-gorli** [opensds/multi-cloud#137]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
1. Create Bucket Life Cycle Config rule
2. Create 2nd rule
3. Only second one exists.. (Latest)
**What you expected to happen**:
Should maintain all rules created
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
@satya-gorli Which version you used to do this test? I used the latest code of development branch to test, it works fine, please update the code and test. Thank you.

**Comment by nguptaopensds** [comment]
@satya-gorli I have checked in the updated code for PUT bucket lifecycle as a part of "https://github.com/opensds/multi-cloud/pull/132" (Restore and HEAD API for object). And I have tested it also, need to do some dashboard changes, which @jimccfun  will take care.

**Comment by jimccfun** [comment]
@satya-gorli this issue is not connected to restore , and use the latest code of development branch to test, it works fine.

**Comment by nguptaopensds** [comment]
I am raising a new PR for the fix and detach it from restore PR. Then we can track that PR separately

**Comment by nguptaopensds** [comment]
This issue is fixed as a part of PR #146
