### ISSUE TITLE
Some conflicts appeared when I set two rules of crossed-cloud transition and in-cloud transition

### ISSUE THREAD

**Issue by wisererik** [opensds/multi-cloud#140]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

Some conflicts appeared when I set two rules of crossed-cloud transition and in-cloud transition:

1. Firstly I use crossed-cloud transition rule on objects of aws_1, all objects were transmitted to aws_2 from aws_1, then I created a new rule based on in-cloud and disabled crossed-cloud rule, like the bellowing:

![Selection_009](https://user-images.githubusercontent.com/9572954/59213971-b7d41280-8bd3-11e9-97be-1940aadb7bb3.png)

2. it's weird that all the objects of aws_1(standard) were not transmitted to aws_1(standard ia). 
![Selection_008](https://user-images.githubusercontent.com/9572954/59214160-2022f400-8bd4-11e9-9c96-c212504084de.png)

**What you expected to happen**:

In-cloud transition rule is only applied to aws_1 but it didn't happen.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version: development branch
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wisererik** [comment]
@nguptaopensds @sfzeng please take a look

**Comment by sfzeng** [comment]
The reason is the rule ttt is disabled before enabled, and there is a bug that when a rule disabled, the prefix of that rule will be changed unexpectedly, and this bug is about another project which is dashboard, need dashboard to fix.

**Comment by skdwriting** [comment]
Please check and close. Let us complete within RC2 and raise the PR. Thanks
