### ISSUE TITLE
PUT lifecycle API does not update/modify the rule

### ISSUE THREAD

**Issue by nguptaopensds** [opensds/multi-cloud#154]
**Is this a BUG REPORT or FEATURE REQUEST?**:
>
 /kind feature

**What happened**:
PUT bucket lifecycle always add new rule even if the request is to update the existing one.
**What you expected to happen**:
PUT bucket lifecycle API should modify the existing rule and update the database
**How to reproduce it (as minimally and precisely as possible)**:
1.Create one rule using dashboard
2.Try to edit the same rule giving different value to field
3.It will add another rule in the configuration
**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skdwriting** [comment]
moving to backlog

**Comment by nguptaopensds** [comment]
Fixed in daito
