### ISSUE TITLE
DataLifeCycle-initializingStorageClass for UserDefinedStorage..its wrong

### ISSUE THREAD

**Issue by satya-gorli** [opensds/multi-cloud#166]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
**What happened**:
In Service.go file, initStorageClass() function loads the Storage classes and Transistions based on Env variable USE_DEFAULT_STORAGE_CLASS
If value of this variable is non positive zero, loads default storage and transitions
else should load user defined ones
But if value is zero or negative, its loading Default Transitions instead of User Defined Transitions
**What you expected to happen**:
If value is less than 1, should load User Defined Transitions
**How to reproduce it (as minimally and precisely as possible)**:
![loadDefaultStorage](https://user-images.githubusercontent.com/48289385/60806384-b0068000-a137-11e9-85ae-6bb9d31341ae.PNG)

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nguptaopensds** [comment]
This issue is fixed as a part of #168
