### ISSUE TITLE
Multi-tenant is not supported.

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#171]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Multi-tenant is not supported. 
>
> /kind bug

**What happened**:
1. Login with one user, and create a bukcet.
2. Login with another user which belongs to a different tenant, and still can see the bucket created in step 1.

**What you expected to happen**:
User cannot see the bucket belongs to another tenant.

**How to reproduce it (as minimally and precisely as possible)**:
Do as the steps list above.

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
IMO, this should be a must have feature/fix. @sfzeng @skdwriting Please let me know your opinion. 
We are enhancing the next release with some of the key security features and this should be must have.

**Comment by sfzeng** [comment]
Guys from YIG is working on it,  they will create PR recently.
