### ISSUE TITLE
Error "The specified backend does not exists."  while creating bucket on a storage backend

### ISSUE THREAD

**Issue by d-apurva** [opensds/multi-cloud#61]
The steps to reproduce this error is as follows:
1. I have installed all the required dependencies on **Ubuntu 16.04** as mentioned in the installation and testing document.
2. When I test the curl command to **register AWS  S3  as a storage backend**, the name(bucket name of AWS S3) parameter provided is already created on AWS. This command gives proper response even if the access key or security key provided is invalid.
3. While **Creating bucket on the storage backend**, I get error as {"code":"404","message":"**The specified backend does not exists.**"}.
     Please help me with this error. Thanks in advance.
The screenshot is also provided to reffer the error

![capture](https://user-images.githubusercontent.com/23077957/48536176-c2dff200-e8d3-11e8-99bc-3128cbb9af96.PNG)

**Comment by liuqinguestc** [comment]
hi d-apurva: 
          thank you for your question,because the backend type has been transfered from aws to aws-s3,we will solve the problems as soon as possible

**Comment by d-apurva** [comment]
Thanks for the reply @liuqinguestc , it worked for me.
