### ISSUE TITLE
Enable bucket versioning-Azure

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/multi-cloud#611]

**Comment by skdwriting** [comment]
@nguptaopensds so many issues. Hard to track right? Will it be better we combine the issues based on the development plan (as it is dev issues)? Esp operations for the same cloud provider?
Also, do not see updates on these issues for the progress. Please do update accordingly.

**Comment by nguptaopensds** [comment]
PR #739 resolves the Enabling of versioning on bucket , The PR is for PUT bucket versioning

**Comment by rhsakarpos** [comment]
#612
