### ISSUE TITLE
DELETE bucket SSE-KMS-HWS

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/multi-cloud#677]

**Comment by skdwriting** [comment]
@rhsakarpos why is this removed from Daito SODA v1.0 ? I see many issues , the tag is removed.
Some comments on overall issues:
a) Too many very small issues and hard to track and manage. Please combine bucket operations together for a feature and for a particular cloud. Also if the backend changes are similar for multiple clouds, then, you can combine such as well. As these are development-related issues, let us make the issues accordingly rather too many.
This is applicable for all issues please.

**Comment by rhsakarpos** [comment]
#687
