### ISSUE TITLE
please change ALL time fields to support date and time with timezone

### ISSUE THREAD

**Issue by sunfch** [opensds/multi-cloud#681]
please change ALL time fields to support date and time with timezone

_Originally posted by @rhsakarpos in https://github.com/opensds/multi-cloud/pull/191_

**Comment by sunfch** [comment]
@rhsakarpos ,  @sfzeng   I found that the TIMESTAMP data type has timezone infomation, but the range for TIMESTAMP values only is '1970-01-01 00:00:01.000000' to '2038-01-19, and the range for DATETIME values is '1000-01-01 00:00:00.000000' to '9999-12-31 23:59:59.999999'. 
The UTC time must be stored in variable of DATETIME type, and I think DATETIME meet our requirement.
What about your suggestion?

**Comment by rhsakarpos** [comment]
Sure, if no current usecase needs the timestamp, then DATETIME is okay. however, if you are adding any new DATE or TIME data, please add with timestamp.

**Comment by sunfch** [comment]
DATETIME is satisfied for current usecase, so close the issue
