### ISSUE TITLE
Support SSE server managed key for AWS, GCP, HWS, AZURE and YIG

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/multi-cloud#685]
**FEATURE REQUEST to support SSE with Server managed keys**:

/kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rhsakarpos** [comment]
depends on #633 #634

**Comment by rhsakarpos** [comment]
PR is raised https://github.com/opensds/multi-cloud/pull/729

**Comment by kumarashit** [comment]
UI PR Raised. Blocked for GET Object Listing

**Comment by rhsakarpos** [comment]
@sfzeng please reopen in case needed, marking this closed
