### ISSUE TITLE
Support GET Object for AWS, GCP, HWS, AZURE and YIG backend

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#689]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

> /kind feature

**Anything else we need to know?**:
Both for object less than 5G, and object more than 5G.

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hopkings2008** [comment]
close this issue since it is already finished.
