### ISSUE TITLE
Support PUT Object for AWS, GCP, HWS, AZURE and YIG

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#690]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind feature

**Anything else we need to know?**:
Include single PUT and Multi-part PUT, for Multi-part PUT, include :
InitMultiPartUpload, UploadPart, CompleteMultipartUpload, DeleteMultipartUpload

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hopkings2008** [comment]
close this since it is already finished.
