### ISSUE TITLE
Support lifecycle management

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#694]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind feature

**Anything else we need to know?**:
Include: 
1. PUT/GET/DELETE lifecycle rules, API should be compatible with AWS S3.
2. Lifecycle management should support expiration, in-cloud transition and cross-cloud transition.
3. Refactor lifecycle management based on COPY-Object API provided by OpenSDS S3 service.

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
PR is raised
