### ISSUE TITLE
Support COPY Object among AWS, GCP, HWS, AZURE and YIG

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#695]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

> /kind feature

**Anything else we need to know?**:
1. Objects can be copied from one backend to another.
2. Copy can support any size of object, less than 5G or more than 5G.

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
PR is raised for in-cloud copy object for AWS Backend

**Comment by hopkings2008** [comment]
close this since it is already finished.
