### ISSUE TITLE
Garbage collection implementation in multi-cloud (sync up from YIG)

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#697]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind feature

**Anything else we need to know?**:
1. Need to clean up data for those deleted objects.
2. Need to consider those unfinished upload parts.

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hopkings2008** [comment]
both the yig backend and s3 have gc logic separately. currently, the gc of yig backend is still under review.

**Comment by hopkings2008** [comment]
close this since it is already finished.
