### ISSUE TITLE
change database name s3

### ISSUE THREAD

**Issue by sunfch** [opensds/multi-cloud#707]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
now database name is yig

**What you expected to happen**:
change database name s3

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
@sunfch Please update

**Comment by sfzeng** [comment]
It is fixed in PR#708
