### ISSUE TITLE
can not upload null file

### ISSUE THREAD

**Issue by sunfch** [opensds/multi-cloud#710]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
can not upload null file
**What you expected to happen**:
can upload file with 0 byte size
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
It is fixed in PR#712.
