### ISSUE TITLE
Data in Tidb would be lost if we stop and remove the docker

### ISSUE THREAD

**Issue by ThisIsClark** [opensds/multi-cloud#716]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
We store some data in Tidb, but when we docker-compose down then docker-compose up -d, data in Tidb would be lost.

**What you expected to happen**:
Data would not be lost no matter when we docker-compose down.

**How to reproduce it (as minimally and precisely as possible)**:
Execute docker-compose down then docker-compose up -d, check whether your data in Tidb is still existed.

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version: latest
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux node01 4.4.0-62-generic
- Install tools:
- Others:

**Comment by sfzeng** [comment]
It is fixed in PR#718
