### ISSUE TITLE
GET Object with SSE

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/multi-cloud#733]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
kind feature

**What happened**:

**What you expected to happen**:
If SSE is set on the bucket and an object GET is done for an object in this bucket, the object is got from the backend and decrypted in OSDS

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rhsakarpos** [comment]
PR is raised #729
UI integration pending, plan to complete on 21/11

**Comment by kumarashit** [comment]
@anvithks Can you please check this issue and if there is no action required, please close it

**Comment by rhsakarpos** [comment]
@sfzeng please reopen in case needed, marking this closed
