### ISSUE TITLE
Is it better to do encryption in s3 service than in api service?

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/multi-cloud#772]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Is it better to do encryption in s3 service than in api service?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
It's fixed in PR#787. Encryption and decryption is moved from API to s3 service.
