### ISSUE TITLE
Valid Canned ACL

### ISSUE THREAD

**Issue by sunfch** [opensds/multi-cloud#775]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**Anything else we need to know?**:
valid acl rule in s3 API and improve PutObject API

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
This is fixed in PR#775
