### ISSUE TITLE
Add uploadpart table to support all kind of backend

### ISSUE THREAD

**Issue by sunfch** [opensds/multi-cloud#781]
because of the lack of upload part table,  we only support yig backend, and we can not get size and etag from some kinds of backend, and we should add the table to calculate  the parameter in multicloud s3 layer.

_Originally posted by @sfzeng in https://github.com/opensds/multi-cloud/pull/769#issuecomment-562402832_

**Comment by skdwriting** [comment]
@sunfch , can we specifiy which are the backend supported and which are not. It will make it clear.

**Comment by sunfch** [comment]
> @sunfch , can we specifiy which are the backend supported and which are not. It will make it clear.

I will add it in the RN of the PR

**Comment by sunfch** [comment]
have supported in PR#797
