### ISSUE TITLE
api crash when grpc server failed

### ISSUE THREAD

**Issue by sunfch** [opensds/multi-cloud#810]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
api crashed when s3 return error

**What you expected to happen**:
api should not crashed and return error to client user when s3 return error
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
It's fixed by PR#811&PR#842.
