### ISSUE TITLE
Support the API of CopyPart

### ISSUE THREAD

**Issue by sunfch** [opensds/multi-cloud#817]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**Anything else we need to know?**:
CopyPart API: Uploads a part by copying data from an existing object as data source. the requirement is from https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html. Precondition feature for CopyPart is supported in the PR

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
It's fixed by PR#818
