### ISSUE TITLE
Upload Object failed while using Ceph as a backend

### ISSUE THREAD

**Issue by Click2Cloud-Gamma** [opensds/multi-cloud#836]
**Is this a BUG REPORT or FEATURE REQUEST?**:
kind bug

**What happened**:
I am not able to upload object while using Ceph Backend. But I am able to upload and migrate objects using other backends like AWS & Azure.

**What you expected to happen**:
1. User should be able to upload object while using Ceph Storage.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Multi-cloud Project
2. Configure Ceph as a Backend. (Created Successfully)
3. Create Bucket (Created successfully)
4. Try to upload Object into that Bucket: It will show `object upload successfully` but in real bucket no object was found and in OpenSDS UI too it will not show any objects in that bucket.

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version: development
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`):  Linux ubuntu 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:
Error Log where Object Upload Failed:
![image](https://user-images.githubusercontent.com/45617130/71405853-98c33c80-265c-11ea-8319-e4ad52dd7aed.png)

And also mysql container exited on running docker-compose
![image](https://user-images.githubusercontent.com/45617130/71405918-c01a0980-265c-11ea-81c2-fb271974c59a.png)

**Comment by sfzeng** [comment]
Hi @Click2Cloud-Gamma , could you please check if the bucket related backend exist or not?

**Comment by Click2Cloud-Gamma** [comment]
> Hi @Click2Cloud-Gamma , could you please check if the bucket related backend exist or not?

It exists, bucket was present in Ceph. I am also trying to figure out the reason behind this issue.
Thanks.

**Comment by sfzeng** [comment]
It's fixed in PR#852.
