### ISSUE TITLE
Lifecycle issue: metadata is not changed once lifecycle operation happened

### ISSUE THREAD

**Issue by wisererik** [opensds/multi-cloud#838]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Cannot download object after data lifecycle task happend:
![image](https://user-images.githubusercontent.com/9572954/71416848-5c0d3a80-2688-11ea-9971-07ecbd7c48b8.png)

![image](https://user-images.githubusercontent.com/9572954/71417000-0f762f00-2689-11ea-9ceb-bf4ae98c7688.png)

**What you expected to happen**:
Can download object after data lifecycle task happend

**How to reproduce it (as minimally and precisely as possible)**:
1. create lifecycle configuration with rule of migrating after expire
2. upload object
3. change time of object 
4. download object after lifecycle operation is finished.

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
Fixed by [839](https://github.com/opensds/multi-cloud/pull/839)
