### ISSUE TITLE
Download failed when using ceph as the backend and enable SSE.

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#869]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
1. Creat a bucket using ceph as it's backend, and enable SSE.
![ceph_bucket_sse](https://user-images.githubusercontent.com/38932432/71779532-00c93980-2ff2-11ea-89f0-6e9a850c6a5f.png)
2. Upload an object:
![ceph_sse_upload](https://user-images.githubusercontent.com/38932432/71779582-29513380-2ff2-11ea-8727-7c42ea599a59.png)
3. Download it failed:
![ceph_sse_download_failed](https://user-images.githubusercontent.com/38932432/71779613-4554d500-2ff2-11ea-93e3-04f45c54a652.png)
4. Check log:
![ceph_sse_download_failed_log](https://user-images.githubusercontent.com/38932432/71779616-556cb480-2ff2-11ea-99ee-d612ef11beed.png)

**What you expected to happen**:
Download it successfully.

**How to reproduce it (as minimally and precisely as possible)**:
See the above steps.

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rhsakarpos** [comment]
@sfzeng please reopen in case needed, marking this closed
