### ISSUE TITLE
The PostObject with yig storage backend may fail to save object data due to the hang of read operation.

### ISSUE THREAD

**Issue by hopkings2008** [opensds/multi-cloud#875]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is a bug, and it is only related to yig storage backend when perform post object.
If yig backend reads data and it meets the eof but the returned data size is not 0, the yig backend will hang there because it will try to read more data from the upper reader. 
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
When perform PostObject with yig storage backend, yig may fail to save the object data.
**What you expected to happen**:
yig backend can save the object data successfully when perform PostObject operation.

**How to reproduce it (as minimally and precisely as possible)**:
PostObject with 1024 data size and use yig storage backend may reproduce this issue.

**Anything else we need to know?**:
it is only related to yig storage backend when perform post object.
If yig backend reads data and it meets the eof but the returned data size is not 0, the yig backend will hang there because it will try to read more data from the upper reader. 

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Fixed
