### ISSUE TITLE
s3 server crashed caused by gc.

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#879]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
s3 server crashed, and got log as below:
![gc_crash](https://user-images.githubusercontent.com/38932432/72031545-a10bb080-32c7-11ea-8d8f-9d6d63233abb.png)

**What you expected to happen**:
s3 server runs normally, no crash.

**How to reproduce it (as minimally and precisely as possible)**:
Just run multi-cloud, normally, it happens randomly.

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Fixed
