### ISSUE TITLE
Download object failed.

### ISSUE THREAD

**Issue by sfzeng** [opensds/multi-cloud#887]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Upload a file which only contains an 'abc' string, then download it, download runs failed,  and got error log as below:
![download_failed_20200203](https://user-images.githubusercontent.com/38932432/73640994-3ec98400-46aa-11ea-8804-542fd4633fef.png)

**What you expected to happen**:
The file can be download successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps described above.

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Fixed.
